[base]
  database_name="volcano_user_srv"
  # 这里有个坑  multiStatements
  migrate_link="root:123456@tcp(127.0.0.1:3307)/volcano_user_srv?charset=utf8&parseTime=true&loc=Asia%2FShanghai&multiStatements=true"
  migrate_path="/Users/max/Documents/coding/Backend/Golang/Personal/volcano/user_srv/migration"
