[base]
    host="0.0.0.0"
    port=8848
    namespace="5a9dd777-c218-4532-a308-a3eddbec1c5a"
    user="nacos"
    password="nacos"
    dataid="user_srv_dev.json"
    group="DEFAULT_GROUP"
    log_dir="/Users/max/Documents/coding/Backend/Golang/Personal/volcano/user_srv/nacos_dir/nacos/log"
    cache_dir="/Users/max/Documents/coding/Backend/Golang/Personal/volcano/user_srv/nacos_dir/nacos/cache"
    max_age=24
    log_level="debug"
    rotate_time="1h"
    time_out=5000
    not_load_cache_at_start=true
    max_backup=3






