[base]
    host="192.168.0.104"
    port=8849
    namspace="3d6a2af2-3f81-4819-815b-bb375034092b"
    user="nacos"
    password="nacos"
    dataid="user_srv_dev.json"
    group="dev"
    log_dir="tmp/nacos/log"
    cache_dir="tmp/nacos/cache"
    max_age=24
    log_level="debug"
    rotate_time="1h"
    time_out=5000
    not_load_cache_at_start=true